config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'feed#index'
  get '/welcome', to: 'welcome#index'
  get 'auth/:provider/callback', to: "sessions#omniauth"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  resources :contents, only: [:show, :destroy]
  resources :notes, only: [:destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  # resources :mixes
  resources :users do
    resources :mixes
    get '/following', to: 'users#following'
    get '/followers', to: 'users#followers'
  end
  resources :follow_relationships, only: [:create, :update, :destroy]

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :mix
  has_rich_text :content
  validates :content, presence: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in?
  def create
    if current_user
      comment = Comment.new(comment_params)
      comment.user_id = current_user.id
      comment.save
      redirect_to request.referrer
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to request.referrer
  end
  private

  def comment_params
    params.require(:comment).permit(:mix_id, :content)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def delete_comment(comment)
      if @current_user == comment.user
        button_to comment_path(comment),method: :delete, class: "comment-button" do 
          "<svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-trash' viewBox='0 0 16 16'>
          <path d='M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z'/>
          <path fill-rule='evenodd' d='M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z'/>
          </svg>".html_safe
        end
      end
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <div class="comment">
    <div class="row">
        <div class="col-sm">
          <%=link_to(comment.user.username, user_path(comment.user))%>
          <img class="comment-profile-img"src="<%=comment.user.image%>">
        </div>
        <div class="col-sm">
          <%=delete_comment(comment)%>
        </div>
    </div>
    <div class="row">
      <div class="col-sm">
        <div class="comment-content">
          <%=comment.content%>
        </div>
      </div>    
    </div>
  </div>
<%end%>
    

app/views/comments/_comments.html.erb
    <div class="comments-container jumbotron">
      <h5>Comments:</h5>  
      <div class="comments">
        <%= turbo_stream_from "#{mix.id}comments" %>
        <%= turbo_frame_tag "#{mix.id}comments" do %>
          <%=render mix.comments%>
        <%end%>
      </div>
      <div class="new-comment-container">
        <%= render partial: 'comments/new', locals: {mix: mix}%>
      </div>
    </div>

app/views/comments/_new.html.erb
<div class="new-comment">
  <!--<%if current_user%>-->
    <%=form_for mix.comments.build do |f|%>
      <%=f.hidden_field :mix_id, value: mix.id%>
      <%=f.rich_text_area :content, required: true, id: "trix#{mix.id}", class: "comment-editor", placeholder: "New Comment"%>
      <%= button_tag( :class => "comment-button") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
      </svg>
      <% end %>
    <%end%>
  <!--<%else%>
    <%=button_to "Login to add comments", login_path, method: :get%>
  <%end%>-->
</div>