config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'feed#index'
  get '/welcome', to: 'welcome#index'
  get 'auth/:provider/callback', to: "sessions#omniauth"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  resources :contents, only: [:show, :destroy]
  resources :notes, only: [:destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  # resources :mixes
  resources :users do
    resources :mixes
    get '/following', to: 'users#following'
    get '/followers', to: 'users#followers'
  end
  resources :follow_relationships, only: [:create, :update, :destroy]

end

app/models/mix.rb
class Mix < ApplicationRecord
  has_rich_text :description
  belongs_to :user
  has_many :mix_contents
  has_many :contents, through: :mix_contents
  has_many :likes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :notes, :dependent => :destroy
 
  validates :title, presence: true, length: {in: 1..30}

  accepts_nested_attributes_for :contents
  accepts_nested_attributes_for :notes, reject_if: proc {|attributes| attributes[:text].blank?}

  scope :most_recent, -> {all.order(updated_at: :desc)}
  scope :sort_by_recent, ->(ids) {most_recent.where(id: ids)}



  def last_updated
    updated_at.strftime("%A, %b %d")
  end

  def self.get_by_query(q)
    by_title = Mix.includes(:contents, :user, :rich_text_description, :comments).all.select{|m|m.title.downcase.include?(q.downcase)}
    content = Content.includes({:mix_contents => :content}).search_by_q(q)
    by_content = Mix.includes(:contents, :user, :rich_text_description, :comments).all.select{|m|(m.contents & content).present?}
    (by_title + by_content).uniq
  end

  def sort_contents_by_recent
    # contents.sort_by{|c|c.mix_contents.collect{|mc|mc.updated_at}}.reverse
    contents.sort_by{|c|c.mix_contents.select{|mc|mc.mix == self}.sort_by{|mc|mc.created_at}}
  end
end

app/controllers/mixes_controller.rb
class MixesController < ApplicationController
  include MixesHelper
  before_action :logged_in?, :set_current_user

  def index
    @user = User.includes(:avatar_attachment, :following,
            :mixes => [:rich_text_description, {:comments => [:user, :rich_text_content]}, :contents]
            ).find(params[:user_id])
    @mixes = @user.mixes
  end

  def new 
    @mix = Mix.new
  end

  def create
    @mix = current_user.mixes.find_or_create_by(mix_params)
    @mix.description = params[:mix][:description] unless params[:mix][:description].blank?
    
    if @mix.save
      if params[:content]
        content =  Content.find_or_create_by(content_params)
        @mix.contents <<  content unless @mix.contents.include?(content)
      else
        redirect_to user_mix_path(current_user, @mix)
      end
    else
      render :new
    end
    
  end

  def show
    @mix = Mix.includes(:user, {:comments => [:user, :rich_text_content]}).find(params[:id])
  end

  def edit
    @mix = Mix.find(params[:id])
  end

  def update
    @mix = Mix.find(params[:id])
    if @mix.update(mix_update_params)
      redirect_to user_mix_path(current_user, @mix)
    else
      render :edit
    end
  end

  def destroy
    @mix = Mix.find(params[:id])
    @mix.destroy
    redirect_to user_mixes_path(current_user)
  end

  private

  def set_current_user
    @current_user = current_user
  end

  def mix_params
    params.require(:mix).permit(:title)
  end

  def content_params
    params.require(:content).permit(:data_type, :title, {creators: []}, :date, :image, :url, :description)
  end

  def mix_update_params
    params.require(:mix).permit(:title, :description, notes_attributes: [:text, :content_id, :id])
  end
end

app/helpers/mixes_helper.rb
module MixesHelper
  def edit_link(mix)
    if access(mix)
      link_to(edit_user_mix_path(mix.user, mix)) do
        "<svg xmlns='http://www.w3.org/2000/svg' width='20' height='20' fill='currentColor' class='bi bi-pencil-square' viewBox='0 0 16 16'>
        <path d='M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z'/>
        <path fill-rule='evenodd' d='M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z'/>
        </svg>".html_safe
      end
    end
  end

  def delete_link(mix)
    if access(mix)
      link_to(user_mix_path(mix.user, mix), method: :delete, data: { confirm: 'Are you sure want to delete this?' } ) do
        "<svg xmlns='http://www.w3.org/2000/svg' width='20' height='20' fill='currentColor' class='bi bi-trash' viewBox='0 0 16 16'>
          <path d='M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z'/>
          <path fill-rule='evenodd' d='M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z'/>
        </svg>".html_safe
      end
    end
  end

  def new_link
    if @current_user.id == params[:user_id].to_i
      render partial: 'mixes/new_mix_card'
    end
  end

  def no_contents(mix)
    if access(mix)
      if mix.contents.empty?
        link_to "Feeling empty. Time to add items to this mix!", "/welcome"
      end
    end
  end

  def access(mix)
    if @current_user
      if @current_user.id == mix.user_id
        true
      end
    end
  end


end

app/views/mixes/_add_to_form.html.erb
<div class="add-to-form">
  <%if @current_user%>
    <%=form_with model: @current_user.mixes.build, url: user_mixes_path(@current_user) do |f|%>
      <%=fields_for Content.new do |c|%>
        <%=c.hidden_field :data_type, value: media[:data_type]%>
        <%=c.hidden_field :title, value: media[:title]%>
        <%media[:creators].each do |creator|%>
          <input type="hidden" name="content[creators][]" value="<%=creator%>">
        <%end unless media[:creators].nil?%>
        <%=c.hidden_field :date, value: media[:date]%>
        <%=c.hidden_field :image, value: media[:image]%>
        <%=c.hidden_field :url, value: media[:url]%>
        <%=c.hidden_field :description, value: media[:description]%>
      <%end%>

        <%=f.text_field 'title', list: 'title', required: true, autocomplete: 'off', placeholder: "Add to new or existing mix"%> 
      <datalist id="title">
        <%@current_user.mixes.each do |m|%>
          <option value="<%=m.title%>"></option>
        <%end%>
      </datalist>
        <%=button_tag class: "add-to-button" do%>
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-patch-plus-fill" viewBox="0 0 16 16">
            <path d="M10.067.87a2.89 2.89 0 0 0-4.134 0l-.622.638-.89-.011a2.89 2.89 0 0 0-2.924 2.924l.01.89-.636.622a2.89 2.89 0 0 0 0 4.134l.637.622-.011.89a2.89 2.89 0 0 0 2.924 2.924l.89-.01.622.636a2.89 2.89 0 0 0 4.134 0l.622-.637.89.011a2.89 2.89 0 0 0 2.924-2.924l-.01-.89.636-.622a2.89 2.89 0 0 0 0-4.134l-.637-.622.011-.89a2.89 2.89 0 0 0-2.924-2.924l-.89.01-.622-.636zM8.5 6v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 1 0z"/>
          </svg>
        <%end%>
    <%end%>
  <%else%>
    <%=link_to 'Login to add to a mix!', '/login', class:"btn-sm"%>
  <%end%>
</div>

app/views/mixes/_form.html.erb
<div class="mix-edit form-outline text-center">

<%=render partial: 'shared/errors', locals: {obj: @mix}%>

  <%=form_for [@current_user, @mix] do |f|%>
    <%=f.text_field :title, placeholder: "Title", class: "form-control-lg text-center", style: "width: 100%"%>
    <br><br>
    <div class="jumbotron">
      <%=f.label :description%>
      <br>
      <%=f.rich_text_area :description%>
    </div>
    <%@mix.contents.each do |c|%>
    <div class="jumbotron">
      <%=link_to "Remove this item from mix", content_path(c, mix_id: @mix.id), method: :delete,data: { confirm: 'Are you sure want to delete this? Any unsaved work will not be saved when deleting.' }%>
      <br>
      <div class="card-container">
        <div class="card">
          <%=render_piece(c)%>
        </div>
      </div>
          <%=f.fields_for :notes, c.specific_notes(@mix) do |note_fields|%>
            <%=note_fields.label "Edit item note:"%>
            <%=note_fields.rich_text_area :text%>
            <%=note_fields.hidden_field :content_id, value: c.id%>
            <%=link_to "Delete note", note_path(note_fields.object.id, mix_id: @mix.id), method: :delete,data: { confirm: 'Are you sure want to delete this? Any unsaved work will not be saved when deleting.' }%>
          <%end%>
        <br><br><br>
        <div class="note">
          <%=f.fields_for :notes, @mix.notes.build do |note_fields|%>
            <%=note_fields.label "New note for this item:"%>
            <%=note_fields.rich_text_area :text%>
            <%=note_fields.hidden_field :content_id, value: c.id%>
          <%end%>
        </div>
    </div>
    <%end%>
    <%=f.submit%>
  <%end%>
</div>

app/views/mixes/_mix.html.erb
 
<div class="mix-container">
  <div class="mix-content">
  <%if no_contents(mix)%>
   <div class="jumbotron mix-header">
    <h1><%=no_contents(mix)%></h1>
   </div>
  <%end%>
   <div class="jumbotron mix-header p-3">

      <h3><%=link_to mix.title, user_mix_path(mix.user, mix)%></h3>
      <h5>By <%=link_to mix.user.username, user_path(mix.user)%></h5>
      <%=profile_image(mix.user)%>
      <br><br>
      <i><%=mix.last_updated%></i>
      <br><br>
      <%=render partial: 'likes/like', locals: {mix: mix}%>
      <div class="edit-delete">
        <%=edit_link(mix)%><%=delete_link(mix)%>
      </div>
      

    </div>
      <%if mix.description.present?%>
        <div class="jumbotron">
          <i><%=mix.description%></i>
        </div>
      <%end%>
    
      <%mix.contents.each do |content|%>
        <div class="jumbotron">
          <%=render partial: 'contents/content', locals: {content: content}%>
          <%content.specific_notes(mix).each do |note|%>
            <%=render partial: 'notes/note', locals: {note: note}%>
          <%end%>
        </div> 
      <%end%>
     
      <%=render partial: 'comments/comments', locals: {mix: mix}%>


  </div>
</div>

app/views/mixes/_mix_preview.html.erb
  <div class='card-container hover-shadow'>
    <div class='card' >
      <div class="mix-preview">
      <%=render partial: 'mixes/mix', locals: {mix: mix}%>
      </div>
    </div>
  </div> 

app/views/mixes/_new_mix_card.html.erb
<div class='card-container'>
  <div class="card">
    <div class="mix-header">
      <h1 style="margin-top: 100px"><%=link_to "New Mix", new_user_mix_path(@current_user)%></h1>
    </div>
  </div>
</div>

app/views/mixes/edit.html.erb
<h1 class="text-center">Edit Mix</h1>
<%=render 'form'%>

app/views/mixes/index.html.erb
<div class="mix-index album ">
  <div class="row">
    <div class="col-md-12 text-center">
      <h2 style="max-width: 100%; word-wrap: break-word"><%=@user.username%>'s Collection</h2> 
      <hr>
      <%=render partial: 'users/user', locals: {user: @user}%>
    </div>     
  </div>

  <div class="row">
    <div class="col-md-12 text-center">
      <div class="album " style="width: 80%; margin: auto">
        <%=new_link%>   
        
        <%@mixes.each do |m|%>
          <%=render partial: 'mix_preview', locals: {mix: m}%>
        <%end%>
      </div>
      <hr>
      <h3>Liked Mixes</h3>
      <div class="album py-5" style="width: 80%; margin: auto">
        <%@user.liked_mixes.each do |m|%>
          <%=render partial: 'mix_preview', locals: {mix: m}%>
        <%end%>
      </div>
      <hr>
      <h3>Commented On</h3>
      <div class="album py-5" style="width: 80%; margin: auto">
        <%@user.commented_mixes.each do |m|%>
          <%=render partial: 'mix_preview', locals: {mix: m}%>
        <%end%>
      </div>
      
      <br>
    </div>
  </div>
</div>

app/views/mixes/new.html.erb
<h1 class="text-center">New Mix</h1>
<%=render 'form'%>

app/views/mixes/show.html.erb
<%=render partial: 'mixes/mix', locals: {mix: @mix}%>