config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'feed#index'
  get '/welcome', to: 'welcome#index'
  get 'auth/:provider/callback', to: "sessions#omniauth"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  resources :contents, only: [:show, :destroy]
  resources :notes, only: [:destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  # resources :mixes
  resources :users do
    resources :mixes
    get '/following', to: 'users#following'
    get '/followers', to: 'users#followers'
  end
  resources :follow_relationships, only: [:create, :update, :destroy]

end

app/models/user.rb
class User < ApplicationRecord

  has_many :mixes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy

  has_many :following, foreign_key: :follower_id, class_name: :FollowRelationship
  has_many :followers, foreign_key: :followed_id, class_name: :FollowRelationship

  has_one_attached :avatar
  has_secure_password

  validates :username, presence: true, length: {in: 1..30}
  validates :email, presence: true, uniqueness: true
  validates :password, length: {in: 7..32}, :if => :password_digest_changed?



  def self.create_from_omniauth(auth)
    self.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
      u.image = auth['info']['image']
      u.username = auth['info']['name']
      u.email = auth['info']['email']
      u.password = SecureRandom.hex(16)
      u.password_confirmation = u.password
    end
  end

  def follow(other_user)
    follow_relationships.create(follower_id: self.id, followed_id: other_user.id)
  end

  def followed_users
    User.includes(:following, :avatar_attachment).where(id: following.map{|fr|fr.followed_id})
  end

  def followed_by
    User.includes(:followers, :avatar_attachment).where(id: followers.map{|fr|fr.follower_id})
    # User.all.select{|user| user.followed_users.include?(self)}
  end

  def following_mixes
    Mix.includes({:contents => :notes}, {:comments => :user}, :user).where(user: followed_users)
  end

  def self.sort_by_followers
    all.sort_by{|u| u.followed_by.count}.reverse
  end

  def feed 
    Mix.includes(:rich_text_description, :contents, {:comments => [:user, :rich_text_content]}, {:user => :avatar_attachment}).where(user: followed_users).or(Mix.where(user: self)).order(updated_at: :desc)
  end
  
  def not_followed_yet
    User.includes(:following, :followers, :avatar_attachment).where.not(id: self.followed_users.ids.push(self.id))
    # User.all.select{|user| !user.followed_by.include?(self) && user != self}.sort_by{|u|u.mixes.length}.reverse()[0..8]
  end

  def liked_mixes
    Mix.includes(:rich_text_description, :contents, {:comments => [:user, :rich_text_content]}, {:user => [:avatar_attachment]}).where(likes: self.likes)
  end

  def commented_mixes
    Mix.includes(:rich_text_description, :contents, {:comments => [:user, :rich_text_content]}, {:user => [:avatar_attachment]}).where(comments: self.comments)
  end

  def my_image 
    if avatar.attached?
      avatar
    else
      image
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :access_user, only: [:edit, :update]
  before_action :get_user, only: [:show, :edit, :update, :following, :followers]
  layout 'login', except: [:edit, :following, :followers]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_mix_path(User.first, Mix.first)
    else
      render :new
    end
  end

  def show
    redirect_to user_mixes_path(@user)
  end

  def edit 
  
  end

  def update
    if @user.update(user_params)
      redirect_to user_mixes_path(@user)
    else
      render :edit
    end
  end

  def following
    @current_user = current_user
    @users = @user.followed_users
  end

  def followers
    @current_user = current_user
    @users = @user.followed_by
  end
  private

  def access_user
    return head(:forbidden) unless get_user == current_user
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end

  def get_user
    if params[:user_id]
      @user = User.find(params[:user_id]) 
    else
      @user = User.find(params[:id])
    end
    
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_image(user)
    if user.avatar.attached?
      "<div class='profile-image'><img src='#{(url_for(user.avatar))}' ></div>".html_safe
    else
      "<div class='profile-image'><img src='#{user.image}' ></div>".html_safe
    end
  end

  def render_follow_form
    # if User.find(params[:user_id]).followed_by.include?(current_user)
    #   form_for current_user.follow_relationships.find_by(followed_id: params[:user_id]), method: :delete do |f|
    #     f.hidden_field :followed_id, value: params[:user_id]
    #     f.submit "Unfollow", class:"btn btn-sm btn-primary w-100 ml-2"
    #   end
    # else
    #   form_for FollowRelationship.new do |f|
    #     f.hidden_field :follower_id, value: current_user.id
    #     f.hidden_field :followed_id, value: params[:user_id]
    #     f.submit "Follow", class:"btn btn-sm btn-primary w-100 ml-2"
    #   end
    # end
  end
end

app/views/users/_follow.html.erb
<%if @current_user.followed_users.include?(user)%>
  <%=form_for FollowRelationship.find_by(followed_id: user.id, follower_id: @current_user.id), method: :delete do |f|%>
  <%=f.hidden_field :followed_id, value: user.id%>
    <div class="button mt-2 d-flex flex-row align-items-center">
      <%=f.submit "Unfollow", class:"btn btn-sm btn-dark w-100"%>
    </div>
  <%end%>
<%else%>
  <%=form_for FollowRelationship.new do |f|%>
    <%=f.hidden_field :follower_id, value: @current_user.id%>
    <%=f.hidden_field :followed_id, value: user.id%>
    <div class="button mt-2 d-flex flex-row align-items-center">
      <%=f.submit "Follow", class:"btn btn-sm btn-dark w-100"%>
    </div>
  <%end%>
<%end%>

app/views/users/_form.html.erb
  <%=render partial: 'shared/errors', locals: {obj: user}%>
  <%=profile_image(user)%>
    <%=form_for user do |f|%>
      <%=f.file_field :avatar, class: "col-sm-9"%>
      <%=f.text_field :username, class:"form-control", placeholder: "Memix Username" %> 
      <%=f.text_field :email, class:"form-control", placeholder: "Your Email" %> 
      <%=f.password_field :password, class:"form-control", placeholder: "Password" %> 
      <%=f.password_field :password_confirmation, class:"form-control", placeholder: "Password Confirmation" %>
      <%=f.submit%>
    <%end%>
 

app/views/users/_user.html.erb
    <div class="justify-content-center user-container">
        <div class="card p-3">
            <div class="align-items-center mx-auto jumbotron">
                <div class="" style="">
                    <h5 class="mb-0 mt-0"><%=link_to user.username, user_mixes_path(user)%></h5>
                        <div class="image">
                            <%=profile_image(user)%>
                        </div>
                        <%if user == @current_user%>
                            <%=button_to edit_user_path(user), method: :get, style: "border: none; background: transparent" do%>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                            </svg>
                            <%end%>
                        <%end%>
                    
                    <div class="d-flex justify-content-between rounded  stats">
                        <div class="col-4"> <div class="articles">Mixes</div> <div class="number1"><%=user.mixes.count%></div> </div>
                        <div class="col-4"> <%=link_to user_followers_path(user) do%><div class="followers">Followers</div><%end%> <div class="number2"><%=user.followed_by.count%></div> </div>
                        <div class="col-4"> <%=link_to user_following_path(user) do%><div class="followers">Following</div><%end%> <div class="number2"><%=user.followed_users.count%></div> </div>
                    </div>
                    <div class="follow-button-container">
                        <%=render partial: 'users/follow', locals: {user: user}%>
                    </div>
                </div>
               
            </div>
        </div>
    </div>

app/views/users/edit.html.erb
<div class="form-signin">
  <div class="card">
    <h2>Edit Profile</h2>
    <%=render partial: 'form', locals: {user: @user}%>
  </div>
</div>

app/views/users/followers.html.erb
    <div class="text-center">
      <h1><%=@user.username%>'s Followers</h1>
       <%@users.each do |u|%>
        <%=render partial: 'users/user', locals: {user: u}%>
      <%end%>
    </div>

app/views/users/following.html.erb
    <div class="text-center">
      <h1><%=@user.username%> is Following</h1>
       <%@users.each do |u|%>
        <%=render partial: 'users/user', locals: {user: u}%>
      <%end%>
    </div>

app/views/users/new.html.erb
<div class="form-signin">
  <div class="card">
    <h3>Feeling mixed up? Create an account!</h3>
    <%=render partial: 'sessions/login_with'%>
    <%=render partial: 'form', locals: {user: @user}%>
    <hr>
    <%=link_to 'Login', '/login', class: 'nav-item nav-link' unless current_user%>
  </div>
</div>