config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'feed#index'
  get '/welcome', to: 'welcome#index'
  get 'auth/:provider/callback', to: "sessions#omniauth"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  resources :contents, only: [:show, :destroy]
  resources :notes, only: [:destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  # resources :mixes
  resources :users do
    resources :mixes
    get '/following', to: 'users#following'
    get '/followers', to: 'users#followers'
  end
  resources :follow_relationships, only: [:create, :update, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeMix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= favicon_link_tag asset_path('/m.png') %>
  </head>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
  <body class="bg-light">
    <br><br>
    <div class="row ">
    
      <div class="col-md-12">
        <h1 class="text-center title"><a href="/welcome" class="">MEMIX</a></h1>
        <div class="pos-f-t">
          <nav class="navbar navbar-light ">
            <button class="navbar-toggler-sm mx-auto" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </nav>
          <br>
          <div class="collapse" id="navbarToggleExternalContent">
            <div class="nav-links row text-center">
              <%=link_to 'Feed', '/', class: 'col-md-4'%>
              <%=link_to 'Collection', user_mixes_path(@current_user), class: 'col-md-4' if @current_user%>
              <%=link_to 'Logout', '/logout', class: 'col-md-4' if @current_user%>
            </div>  
          </div>
        </div>
      </div>
    </div>
    <br>
    <%= render partial: 'welcome/search'%>
    <br>
    
      <%= yield %>
    <div class="album who-to-follow">
      <br><br><br>
      <hr>
      <h1 class="text-center text-color-white">Who to follow</h1>
      <div class="row people-to-follow">
        <div class="col-md-12 text-center">
          <%if @current_user%>
            <%@current_user.not_followed_yet.each do |user|%>
             <%=render partial: 'users/user', locals: {user: user}%>
            <%end%>
          <%end%>
        </div>
      </div>
    </div>
  </body>
  
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeMix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= favicon_link_tag asset_path('/m.png') %>
  </head>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
  <body class="bg-light">
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v9.0&appId=421663072224232&autoLogAppEvents=1" nonce="EoRNr2j1"></script>
    <h1 class="text-center title"><a href="/welcome" class="nav-link">Welcome to MEMIX</a></h1>
    <h5 class="text-center"><i>A creative space to share and discover multimedia content</i></h5>
    <%= yield %>
  </body>
</html>